
package mx.com.televisa.cfdis.service.dbptt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Database_ptt-bindingQSService", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/AN-DS_EDI06/GetStatusEDICOM/Database", wsdlLocation = "http://129.213.35.214:80/Televisa/GetStatusEDICOM?wsdl")
public class DatabasePttBindingQSService
    extends Service
{

    private final static URL DATABASEPTTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATABASEPTTBINDINGQSSERVICE_EXCEPTION;
    private final static QName DATABASEPTTBINDINGQSSERVICE_QNAME = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/AN-DS_EDI06/GetStatusEDICOM/Database", "Database_ptt-bindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/laloc/AppData/Local/Temp/tempdir5675661638480996118.tmp/GetStatusEDICOM_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATABASEPTTBINDINGQSSERVICE_WSDL_LOCATION = url;
        DATABASEPTTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public DatabasePttBindingQSService() {
        super(__getWsdlLocation(), DATABASEPTTBINDINGQSSERVICE_QNAME);
    }

   

    public DatabasePttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, DATABASEPTTBINDINGQSSERVICE_QNAME);
    }

   

    public DatabasePttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

  

    /**
     * 
     * @return
     *     returns DatabasePtt
     */
    @WebEndpoint(name = "Database_ptt-bindingQSPort")
    public DatabasePtt getDatabasePttBindingQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/AN-DS_EDI06/GetStatusEDICOM/Database", "Database_ptt-bindingQSPort"), DatabasePtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DatabasePtt
     */
    @WebEndpoint(name = "Database_ptt-bindingQSPort")
    public DatabasePtt getDatabasePttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/AN-DS_EDI06/GetStatusEDICOM/Database", "Database_ptt-bindingQSPort"), DatabasePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATABASEPTTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw DATABASEPTTBINDINGQSSERVICE_EXCEPTION;
        }
        return DATABASEPTTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
