
package mx.com.televisa.cfdis.service.invptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidarInformacionFactura_ValidarInformacionFactura_REQUEST", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ValidarInformacionFactura")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidarInformacionFacturaValidarInformacionFacturaREQUEST {


    /**
     * 
     * @param input
     * @return
     *     returns mx.com.televisa.cfdis.service.invptt.OutputParameters
     */
    @WebMethod(operationName = "ValidarInformacionFactura", action = "ValidarInformacionFactura")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateInvoiceInfo", partName = "Output")
    public OutputParameters validarInformacionFactura(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateInvoiceInfo", partName = "Input")
        InputParameters input);

}
