
package mx.com.televisa.cfdis.service.invasimiptt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.cfdis.util.LeerProperties;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidarInformacionFactura", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ValidarInformacionFactura", wsdlLocation = "https://\"+LeerProperties.wsOIC+\"/Televisa/ValidateInvoiceInfo?wsdl")
public class ValidarInformacionFactura
    extends Service
{

    private final static URL VALIDARINFORMACIONFACTURA_WSDL_LOCATION;
    private final static WebServiceException VALIDARINFORMACIONFACTURA_EXCEPTION;
    private final static QName VALIDARINFORMACIONFACTURA_QNAME = new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarInformacionFactura", "ValidarInformacionFactura");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://"+LeerProperties.wsOIC+"/Televisa/ValidateInvoiceInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDARINFORMACIONFACTURA_WSDL_LOCATION = url;
        VALIDARINFORMACIONFACTURA_EXCEPTION = e;
    }

    public ValidarInformacionFactura() {
        super(__getWsdlLocation(), VALIDARINFORMACIONFACTURA_QNAME);
    }

    public ValidarInformacionFactura(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDARINFORMACIONFACTURA_QNAME, features);
    }

    public ValidarInformacionFactura(URL wsdlLocation) {
        super(wsdlLocation, VALIDARINFORMACIONFACTURA_QNAME);
    }

    public ValidarInformacionFactura(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDARINFORMACIONFACTURA_QNAME, features);
    }

    public ValidarInformacionFactura(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidarInformacionFactura(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidarInformacionFacturaValidarInformacionFacturaREQUEST
     */
    @WebEndpoint(name = "ValidarInformacionFactura_ValidarInformacionFactura_REQUEST_pt")
    public ValidarInformacionFacturaValidarInformacionFacturaREQUEST getValidarInformacionFacturaValidarInformacionFacturaREQUESTPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarInformacionFactura", "ValidarInformacionFactura_ValidarInformacionFactura_REQUEST_pt"), ValidarInformacionFacturaValidarInformacionFacturaREQUEST.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidarInformacionFacturaValidarInformacionFacturaREQUEST
     */
    @WebEndpoint(name = "ValidarInformacionFactura_ValidarInformacionFactura_REQUEST_pt")
    public ValidarInformacionFacturaValidarInformacionFacturaREQUEST getValidarInformacionFacturaValidarInformacionFacturaREQUESTPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarInformacionFactura", "ValidarInformacionFactura_ValidarInformacionFactura_REQUEST_pt"), ValidarInformacionFacturaValidarInformacionFacturaREQUEST.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDARINFORMACIONFACTURA_EXCEPTION!= null) {
            throw VALIDARINFORMACIONFACTURA_EXCEPTION;
        }
        return VALIDARINFORMACIONFACTURA_WSDL_LOCATION;
    }

}
