
package mx.com.televisa.cfdis.service.cveptt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.cfdis.util.LeerProperties;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarClaveFiscal", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ConsultarClaveFiscal", wsdlLocation = "https://\"+LeerProperties.wsOIC+\"/Televisa/ValidateFiscalKey?wsdl")
public class ConsultarClaveFiscal
    extends Service
{

    private final static URL CONSULTARCLAVEFISCAL_WSDL_LOCATION;
    private final static WebServiceException CONSULTARCLAVEFISCAL_EXCEPTION;
    private final static QName CONSULTARCLAVEFISCAL_QNAME = new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ConsultarClaveFiscal", "ConsultarClaveFiscal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://"+LeerProperties.wsOIC+"/Televisa/ValidateFiscalKey?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARCLAVEFISCAL_WSDL_LOCATION = url;
        CONSULTARCLAVEFISCAL_EXCEPTION = e;
    }

    public ConsultarClaveFiscal() {
        super(__getWsdlLocation(), CONSULTARCLAVEFISCAL_QNAME);
    }

    public ConsultarClaveFiscal(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARCLAVEFISCAL_QNAME);
    }

    public ConsultarClaveFiscal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns ExecutePttGetValidationFileREQUEST
     */
    @WebEndpoint(name = "execute_ptt_GetValidationFile_REQUEST_pt")
    public ExecutePttGetValidationFileREQUEST getExecutePttGetValidationFileREQUESTPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ConsultarClaveFiscal", "execute_ptt_GetValidationFile_REQUEST_pt"), ExecutePttGetValidationFileREQUEST.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePttGetValidationFileREQUEST
     */
    @WebEndpoint(name = "execute_ptt_GetValidationFile_REQUEST_pt")
    public ExecutePttGetValidationFileREQUEST getExecutePttGetValidationFileREQUESTPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ConsultarClaveFiscal", "execute_ptt_GetValidationFile_REQUEST_pt"), ExecutePttGetValidationFileREQUEST.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARCLAVEFISCAL_EXCEPTION!= null) {
            throw CONSULTARCLAVEFISCAL_EXCEPTION;
        }
        return CONSULTARCLAVEFISCAL_WSDL_LOCATION;
    }

}
