
package mx.com.televisa.cfdis.service.cveptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt_GetValidationFile_REQUEST", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ConsultarClaveFiscal")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutePttGetValidationFileREQUEST {


    /**
     * 
     * @param input
     * @return
     *     returns mx.com.televisa.cfdis.service.cveptt.OutputElement
     */
    @WebMethod(operationName = "ConsultarClaveFiscal", action = "ConsultarClaveFiscal")
    @WebResult(name = "OutputElement", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateFiscalKey", partName = "Output")
    public OutputElement consultarClaveFiscal(
        @WebParam(name = "InputElement", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateFiscalKey", partName = "Input")
        InputElement input);

}
