
package mx.com.televisa.cfdis.service.sendasimiptt;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.cfdis.util.LeerProperties;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SendEDICOMProcess",
                  targetNamespace = "http://xmlns.mx.com.televisa/BusinessProcessService/SendFileEdicom/SendEdicom/V1",
                  wsdlLocation =
                  "https://\"+LeerProperties.wsOIC+\"/SendEDICOMRingingAssimilates?wsdl#%7Bhttp%3A%2F%2Fxmlns.mx.com.televisa%2FBusinessProcessService%2FSendFileEdicom%2FSendEdicom%2FV1%7DSendEDICOMProcess")
public class SendEDICOMProcess extends Service {

    private final static URL SENDEDICOMPROCESS_WSDL_LOCATION;
    private final static WebServiceException SENDEDICOMPROCESS_EXCEPTION;
    private final static QName SENDEDICOMPROCESS_QNAME =
        new QName("http://xmlns.mx.com.televisa/BusinessProcessService/SendFileEdicom/SendEdicom/V1",
                  "SendEDICOMProcess");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://"+LeerProperties.wsOIC+"/SendEDICOMRingingAssimilates?wsdl#%7Bhttp%3A%2F%2Fxmlns.mx.com.televisa%2FBusinessProcessService%2FSendFileEdicom%2FSendEdicom%2FV1%7DSendEDICOMProcess");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDEDICOMPROCESS_WSDL_LOCATION = url;
        SENDEDICOMPROCESS_EXCEPTION = e;
    }

    public SendEDICOMProcess() {
        super(__getWsdlLocation(), SENDEDICOMPROCESS_QNAME);
    }

    public SendEDICOMProcess(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDEDICOMPROCESS_QNAME, features);
    }

    public SendEDICOMProcess(URL wsdlLocation) {
        super(wsdlLocation, SENDEDICOMPROCESS_QNAME);
    }

    public SendEDICOMProcess(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDEDICOMPROCESS_QNAME, features);
    }

    public SendEDICOMProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendEDICOMProcess(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SendEdicomService
     */
    @WebEndpoint(name = "SendEdicomService")
    public SendEdicomService getSendEdicomService() {
        return super.getPort(new QName("http://xmlns.mx.com.televisa/BusinessProcessService/SendFileEdicom/SendEdicom/V1",
                                       "SendEdicomService"), SendEdicomService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendEdicomService
     */
    @WebEndpoint(name = "SendEdicomService")
    public SendEdicomService getSendEdicomService(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.mx.com.televisa/BusinessProcessService/SendFileEdicom/SendEdicom/V1",
                                       "SendEdicomService"), SendEdicomService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDEDICOMPROCESS_EXCEPTION != null) {
            throw SENDEDICOMPROCESS_EXCEPTION;
        }
        return SENDEDICOMPROCESS_WSDL_LOCATION;
    }

}
