
package mx.com.televisa.cfdis.service.sendasimiptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.televisa.cfdis.service.sendasimiptt.ObjectFactory;
import mx.com.televisa.cfdis.service.sendasimiptt.Responses;
import mx.com.televisa.cfdis.service.sendasimiptt.SendFileEDICOMReqMsg;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SendEdicomService",
            targetNamespace = "http://xmlns.mx.com.televisa/BusinessProcessService/SendFileEdicom/SendEdicom/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface SendEdicomService {


    /**
     *
     * @param sendEdicomReqMsg
     * @return
     *     returns televisa.com.mx.xmlns.businessobjects.sendedicom.Responses
     */
    @WebMethod(operationName = "SendEdicomConsolidate", action = "SendEdicomConsolidate")
    @WebResult(name = "Responses", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/SendEDICOM",
               partName = "SendEdicomRespMsg")
    public Responses sendEdicomConsolidate(@WebParam(name = "SendFileEDICOMReqMsg",
                                                     targetNamespace =
                                                     "http://xmlns.mx.com.televisa/BusinessObjects/SendEDICOM",
                                                     partName = "SendEdicomReqMsg")
                                           SendFileEDICOMReqMsg sendEdicomReqMsg);

}
