package mx.com.televisa.cfdis.service.sendasimiptt;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1047
public class SendEdicomServiceClient {
    public static void main(String[] args) {
        SendEDICOMProcess sendEDICOMProcess = new SendEDICOMProcess();
        SendEdicomService sendEdicomService = sendEDICOMProcess.getSendEdicomService();
        // Add your code to call the desired methods.


    } 
}
