
package mx.com.televisa.cfdis.service.sendptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://xmlns.oracle.com/AN-DS_EDI06/SendToEDICOM/PS_SendToEdicom")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param input
     * @return
     *     returns mx.com.televisa.cfdis.service.sendptt.Responses
     */
    @WebMethod(operationName = "SendToEdicom", action = "SendToEdicom")
    @WebResult(name = "Responses", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/SendToEdicom", partName = "Output")
    public Responses sendToEdicom(
        @WebParam(name = "opaqueElement", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/SendToEdicom", partName = "Input")
        String input);

}
