
package mx.com.televisa.cfdis.service.eeasimiptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckCompanyExistenceService", targetNamespace = "http://xmlns.mx.com.televisa/BusinessProcessService/CheckCompanyExistence/CheckCompany/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckCompanyExistenceService {


    /**
     * 
     * @param checkCompanyReqMsg
     * @return
     *     returns mx.com.televisa.cfdis.service.eeasimiptt.CheckCompanyRespMsg
     */
    @WebMethod(operationName = "CheckCompanyExistence", action = "CheckCompanyExistence")
    @WebResult(name = "CheckCompanyRespMsg", targetNamespace = "http://xmlns.mx.com.televisa/BusinessServices/CheckCompanyExistence", partName = "CheckCompanyRespMsg")
    public CheckCompanyRespMsg checkCompanyExistence(
        @WebParam(name = "CheckCompanyReqMsg", targetNamespace = "http://xmlns.mx.com.televisa/BusinessServices/CheckCompanyExistence", partName = "CheckCompanyReqMsg")
        CheckCompanyReqMsg checkCompanyReqMsg);

}
