
package mx.com.televisa.cfdis.service.eeptt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt_ConsultarExistenciaEmpresa_REQUEST", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ValidarExistenciaEmpresa")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutePttConsultarExistenciaEmpresaREQUEST {


    /**
     * 
     * @param input
     * @return
     *     returns mx.com.televisa.cfdis.service.eeptt.OutputParameters
     */
    @WebMethod(operationName = "ValidarExistenciaEmpresa", action = "ValidarExistenciaEmpresa")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateExistCompany", partName = "Output")
    public OutputParameters validarExistenciaEmpresa(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.mx.com.televisa/BusinessObjects/Core/CBO/ValidateExistCompany", partName = "Input")
        InputParameters input);

}
