
package mx.com.televisa.cfdis.service.eeptt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.com.televisa.cfdis.util.LeerProperties;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidarExistenciaEmpresa", targetNamespace = "http://xmlns.oracle.com/Retenciones/Retenciones/ValidarExistenciaEmpresa", wsdlLocation = "https://\"+LeerProperties.wsOIC+\"/Televisa/ValidateExistCompany?wsdl")
public class ValidarExistenciaEmpresa
    extends Service
{

    private final static URL VALIDAREXISTENCIAEMPRESA_WSDL_LOCATION;
    private final static WebServiceException VALIDAREXISTENCIAEMPRESA_EXCEPTION;
    private final static QName VALIDAREXISTENCIAEMPRESA_QNAME = new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarExistenciaEmpresa", "ValidarExistenciaEmpresa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://"+LeerProperties.wsOIC+"/Televisa/ValidateExistCompany?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDAREXISTENCIAEMPRESA_WSDL_LOCATION = url;
        VALIDAREXISTENCIAEMPRESA_EXCEPTION = e;
    }

    public ValidarExistenciaEmpresa() {
        super(__getWsdlLocation(), VALIDAREXISTENCIAEMPRESA_QNAME);
    }

    public ValidarExistenciaEmpresa(URL wsdlLocation) {
        super(wsdlLocation, VALIDAREXISTENCIAEMPRESA_QNAME);
    }

    

    public ValidarExistenciaEmpresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   

    /**
     * 
     * @return
     *     returns ExecutePttConsultarExistenciaEmpresaREQUEST
     */
    @WebEndpoint(name = "execute_ptt_ConsultarExistenciaEmpresa_REQUEST_pt")
    public ExecutePttConsultarExistenciaEmpresaREQUEST getExecutePttConsultarExistenciaEmpresaREQUESTPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarExistenciaEmpresa", "execute_ptt_ConsultarExistenciaEmpresa_REQUEST_pt"), ExecutePttConsultarExistenciaEmpresaREQUEST.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePttConsultarExistenciaEmpresaREQUEST
     */
    @WebEndpoint(name = "execute_ptt_ConsultarExistenciaEmpresa_REQUEST_pt")
    public ExecutePttConsultarExistenciaEmpresaREQUEST getExecutePttConsultarExistenciaEmpresaREQUESTPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/Retenciones/Retenciones/ValidarExistenciaEmpresa", "execute_ptt_ConsultarExistenciaEmpresa_REQUEST_pt"), ExecutePttConsultarExistenciaEmpresaREQUEST.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDAREXISTENCIAEMPRESA_EXCEPTION!= null) {
            throw VALIDAREXISTENCIAEMPRESA_EXCEPTION;
        }
        return VALIDAREXISTENCIAEMPRESA_WSDL_LOCATION;
    }

}
